python_tests(
    name = "test_greeting",
    dependencies = [
        "src/python/demo/hello_world/main:hello_world",
        "src/python/demo/lib/demo_plugin:demo_plugin",
    ],
    source = "test_greeting.py",
)
